<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8QG8CLM" failures="1" tests="3" name="Test" time="22.978" errors="0" timestamp="2022-07-26T18:57:18 IST">
  <testcase classname="TestClasses.VerifyUserCanLogIn" name="verifyUserCanLogin" time="2.456"/>
  <testcase classname="TestClasses.VerifyUserCanAddNewAddress" name="verifyUserCanGoToProfilePage" time="4.006"/>
  <testcase classname="TestClasses.VerifyUserCanAddNewAddress" name="veryUserCanAddAddress" time="3.909">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at TestClasses.VerifyUserCanAddNewAddress.veryUserCanAddAddress(VerifyUserCanAddNewAddress.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- veryUserCanAddAddress -->
</testsuite> <!-- Test -->
